version: "3.7"
services:
    dotnetcore-api:
        image: vega/dotnetcore
        build:
            context: ./dotnetcore/
    frontend:
        image: vega/frontend
        build:
            context: ./frontend/
    node-api:
        image: vega/node
        build:
            context: ./node/
    python-api:
        image: vega/python
        build:
            context: ./python
